### ISSUE TITLE
Indexing in Mixed Effect Models

### ISSUE THREAD

**Issue by whatever** [IQSS/ZeligMultilevel#2]
There seems to be an issue with the mixed family of models in Zelig.

This potentially is related to Issue #1

The original thread on the mailing list can be found here:
  https://lists.gking.harvard.edu/pipermail/zelig/2012-February/000999.html

**Comment by cchoirat** [comment]
No longer an issue in Zelig 5

``` r
library(Zelig)

set.seed(1000)

x <- runif(1000, -1, 1)
y <- x + rnorm(1000)
wt <- rexp(1000)
id <- rep(1:20, times = 50)
d <- as.data.frame(cbind(y, x, wt, id))

m1 <- zlsmixed$new()
m1$zelig(y ~ x + (1|id), weights = "wt", data = d)
m1

m2 <- lmer(y ~ x + (1|id), weights = wt, data = d)
summary(m2)
```
